#!/usr/bin/with-contenv bash

# 检查config配置文件，并创建
if [ ! -e "/config/config.yaml" ] ;  then 
cp /app/config.yaml /config/config.yaml
fi

# 检查用户config配置文件，并移动.
if [ -e "/config/config.yaml" ] ;  then
cp /config/config.yaml /app/config.yaml
fi

# 容器启动时下载最新示例文件
rm -f /config/config.yaml.sample
wget -q -O /config/config.yaml.sample https://cdn.jsdelivr.net/gh/allanpk716/ChineseSubFinder/config.yaml.sample
