#!/usr/bin/with-contenv bash

mkdir -p /root/.cache
# permissions
chown -R abc:abc \
    /app \
    /root \
    /config
    
if [ "${PERMS}"=true ]
then
  chown -R abc:abc /media

fi

chmod a+x \
    /app/chinesesubfinder
