name: 编译ChromeChecker

on:
  push:
    tags:
      - v*.*-ChromeChecker*
  workflow_dispatch:

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    name: build chrome_checker
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
          version: latest
          args: release -f .goreleaser-chrome_checker.yml --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
